### ISSUE TITLE
HFlashPlayer not load a flash game

### ISSUE THREAD

**Issue by not-oshi** [h-flash/HFlashPlayer#1]
HFlashPlayer runs when I click "CLICK TO PLAY" ,but only a white screen is visible

**Comment by h-flash** [comment]
please answer the following questions let me try to find out what happened:
1. your location and OS?
2. does the blank window resize by itself after it popped out?
3. click file menu, can you see a url in position 1 like this: "http ..somepath...swf"?
4. can you open the url on your browser?

**Comment by kayupssa** [comment]
I agree. I have the same problem :( It would be better if you share your project on video or in more detail.

**Comment by Amonlol** [comment]
The same problem.
Doesn't work for me wherever I put it (desktop, appdata, program files...).
Tried restarting PC/browser.
Windows 10, Net 4 is installed and all libraries are activated through Control Panel.
The window opens after clicking on the "Click to Play". It looks like something blinks at the top-left side of the flash player's window. And nothing happens, just white screen. As I click on "files" section, it shows me the url, which it tried to open. If I paste that url to my browser, it just asks me to download swf file. After which I can open that file through flash player no problem.

**Comment by h-flash** [comment]
> 
> 
> The same problem.
> Doesn't work for me wherever I put it (desktop, appdata, program files...).
> Tried restarting PC/browser.
> Windows 10, Net 4 is installed and all libraries are activated through Control Panel.
> The window opens after clicking on the "Click to Play". It looks like something blinks at the top-left side of the flash player's window. And nothing happens, just white screen. As I click on "files" section, it shows me the url, which it tried to open. If I paste that url to my browser, it just asks me to download swf file. After which I can open that file through flash player no problem.

It seems everything runs correctly, the blink thing is HFlashPlayer, it start the flashplayer then close it self. And your location please? did you see a browser check when you visit h-flash?

**Comment by Amonlol** [comment]
> It seems everything runs correctly, the blink thing is HFlashPlayer, it start the flashplayer then close it self. And your location please? did you see a browser check when you visit h-flash?

As I said location doesn't matter (for me at least). I've tried some of them: at desktop, in program files (C:\ and D:\), but currently it's located in the local appdata. 

Yes, after I click on "Click to play" button it asks me whether to open HFlashPlayer.

However I've looked at the manual once again and this kinda isn't working.
>3. ... **user admin control pop out** to update registry
>
After opening HFlashPlayer.exe (even as an administrator) nothing pops up as I have to accept\click things. It simply says that "The hflash schema is registered in % my_location%." And the only option I have is to click OK. Should it work as expected?

**Comment by h-flash** [comment]
> 
> 
> > It seems everything runs correctly, the blink thing is HFlashPlayer, it start the flashplayer then close it self. And your location please? did you see a browser check when you visit h-flash?
> 
> As I said location doesn't matter (for me at least). I've tried some of them: at desktop, in program files (C:\ and D:), but currently it's located in the local appdata.
> 
> Yes, after I click on "Click to play" button it asks me whether to open HFlashPlayer.
> 
> However I've looked at the manual once again and this kinda isn't working.
> 
> > 1. ... **user admin control pop out** to update registry
> 
> After opening HFlashPlayer.exe (even as an administrator) nothing pops up as I have to accept\click things. It simply says that "The hflash schema is registered in % my_location%." And the only option I have is to click OK. Should it work as expected?

Ah, I mean, where are you from?  I guess it is because your file download request was blocked by the edge caching server's firewall, did you see a browser checking hint when you visited h-flash?  I leveled down the firewall's security level about a month ago, but looks like that's not the point.

**Comment by Amonlol** [comment]
> ...where are you from?
>
Moldova

> ...did you see a browser checking hint
>
Yes I did. It's always there, when I go to the website. There are no problems yet, not as I can tell. It just lets me log in after a couple of seconds.

> ...your file download request was blocked
>
However, I have absolutely no problem downloading the ".swf" file by clicking the "download" button under the game itself. Or by copying a direct link to my browser from the FlashPlayer's dropdown menu, which should be the same thing.

**Comment by h-flash** [comment]
re-configured firewall again, it should work this time.

**Comment by Amonlol** [comment]
> re-configured firewall again, it should work this time.
>
Yes, it does work indeed. Much appreciate!

**Comment by caneland** [comment]
> please answer the following questions let me try to find out what happened:
> 
> 1. your location and OS?
> 2. does the blank window resize by itself after it popped out?
> 3. click file menu, can you see a url in position 1 like this: "http ..somepath...swf"?
> 4. can you open the url on your browser?

1. Russia and Win 10
2. No, it dosent
3. Yes
4. Yes, but i cant open the file

**Comment by tan09112002** [comment]
how, how to reconfigured it, I off the firewall and downloaded it but it still cannot work
