### ISSUE TITLE
Issue with AMD GPUs

### ISSUE THREAD

**Issue by someonefromthedarkness** [h-flash/HFlashPlayer#19]
As reported here: https://www.reddit.com/r/flash/comments/xg8asz/if_you_have_an_amd_gpu_and_are_struggling_to_play/
the most recent AMD GPU drivers are causing trouble with Flash Player, where whenever you open a .swf file, the window resizes and changes color but you can never see the game.

As it says in the post, it's possible to fix that by changing the settings to disable Hardware Acceleration. However, since this is a standalone version I haven't been able to find a way to change the settings. Would it be possible to do that?

**Comment by h-flash** [comment]
you can try this save file, it located in:
C:\Users\[yourlogin]\AppData\Roaming\Macromedia\Flash Player\macromedia.com\support\flashplayer\sys
[settings.zip](https://github.com/h-flash/HFlashPlayer/files/10279242/settings.zip)

**Comment by someonefromthedarkness** [comment]
I can confirm this fix works, and I'm now able to play all .swf files without any trouble. Thanks!
