### ISSUE TITLE
HFlashPlayer not opening when i clicked on the "Click to play" button

### ISSUE THREAD

**Issue by ARCHIE11222** [h-flash/HFlashPlayer#22]
So yeah i was trying to play one of the game, it works fine until one day when i clicked on the "Click to play" button it won't open anymore
I already have the HFlashPlayer downloaded but still nothing appear when i try to run the game through the HFlashPlayer

**Comment by riradog123** [comment]
> So yeah i was trying to play one of the game, it works fine until one day when i clicked on the "Click to play" button it won't open anymore
> I already have the HFlashPlayer downloaded but still nothing appear when i try to run the game through the HFlashPlayer

**Comment by riradog123** [comment]
> So yeah i was trying to play one of the game, it works fine until one day when i clicked on the "Click to play" button it won't open anymore
> I already have the HFlashPlayer downloaded but still nothing appear when i try to run the game through the HFlashPlayer

**Comment by riradog123** [comment]
[](https://github.com/h-flash/HFlashPlayer/issues/22#issue-1869671487) @ #

**Comment by riradog123** [comment]
/``

**Comment by h-flash** [comment]
Please follow the self check list, no window popped out means not registered correctly, or blocked by something like anti-virus
