### ISSUE TITLE
How can i implement it on my personal (offline) website

### ISSUE THREAD

**Issue by Edoras93** [h-flash/HFlashPlayer#4]
I'd like to implement it on my offline website so i can launch flash games that i have downloaded and implemented in the website jusk clicking on it.
I see that in h-flash website the link of the game is: <a href="hflash://aHR0cHaHau8alk..." target="hflashplayer_open_frame"> but i don't understand what i have to put in href field

Thanks

**Comment by h-flash** [comment]
I just updated how to use for webmasters on readme file.

**Comment by Edoras93** [comment]
Perfect it works!
